-- Sqlite

BEGIN TRANSACTION;

DROP TABLE IF EXISTS Page;
CREATE TABLE Page (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Url TEXT UNIQUE NOT NULL,
    Hash BLOB NOT NULL,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Domain;
CREATE TABLE Domain (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT UNIQUE NOT NULL,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP
);

Drop TABLE IF EXISTS DisallowedPattern;
CREATE TABLE DisallowedPattern (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DomainId INTEGER NOT NULL,
    Pattern TEXT UNIQUE NOT NULL,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DomainId) REFERENCES Domain(Id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS PageLink;
CREATE TABLE PageLink (
    PageId INTEGER PRIMARY KEY,
    Url TEXT NOT NULL
);

COMMIT;