-- Sqlite

BEGIN TRANSACTION;

DROP TABLE IF EXISTS Page;
CREATE TABLE Page (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Url TEXT UNIQUE NOT NULL,
    Hash BLOB NOT NULL,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS BlockedUrls;
CREATE TABLE BlockedUrls (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Url TEXT UNIQUE NOT NULL,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS BlockedUrls;
CREATE TABLE BlockedUrls (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    RootUrl TEXT UNIQUE NOT NULL,
    Modified DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS PageLink;
CREATE TABLE PageLink (
    PageId INTEGER NOT NULL,
    Url TEXT NOT NULL,
    BlockedUrlsId INTEGER NOT NULL,
    FOREIGN KEY (PageId) REFERENCES Page(Id),
    FOREIGN KEY (BlockedUrlsId) REFERENCES BlockedUrls(Id),
    PRIMARY KEY (PageId, Url)
);

COMMIT;