-- Sqlite

BEGIN TRANSACTION;

DROP TABLE IF EXISTS Page;
CREATE TABLE Page (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Url TEXT UNIQUE NOT NULL,
    Hash BLOB NOT NULL,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS BlockedUrl;
CREATE TABLE BlockedUrl (
    RootId INTEGER NOT NULL,
    SubUrl TEXT NOT NULL,
    FOREIGN KEY (RootId) REFERENCES RootUrl(Id)
);

DROP TABLE IF EXISTS RootUrl; /* TODO: add the RootUrl to each page, to save robots_parsing */ 
CREATE TABLE RootUrl (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Url TEXT UNIQUE NOT NULL, 
    Modified DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS PageLink;
CREATE TABLE PageLink (
    PageId INTEGER NOT NULL,
    Url TEXT NOT NULL,
    RootId INTEGER NOT NULL,
    FOREIGN KEY (PageId) REFERENCES Page(Id),
    FOREIGN KEY (RootId) REFERENCES RootUrl(Id),
    PRIMARY KEY (PageId, Url)
);

COMMIT;